name: Find libbz2 dylibs and print install_name

on:
  push:
  workflow_dispatch:

jobs:
  search-libbz2-dylib:
    runs-on: ${{ matrix.macos }}
    strategy:
      matrix:
        macos: [macos-13, macos-14, macos-15]
    steps:
      - uses: casadi/action-setup-compiler@master
        with:
          cache-suffix: ''
          target: ${{matrix.image == 'macos-13' && 'x86_64' || 'arm64'}}
      - name: Find and inspect libbz2 dylibs
        run: |
          echo "Searching for libbz2 dylibs on ${{ matrix.macos }}..."
          SEARCH_PATHS=(
            /usr/lib
            /usr/local
            /opt/homebrew/lib
            /Library/Developer/CommandLineTools/SDKs
            /usr/local/miniconda/
            /Applications
            /Users/runner
          )
          find /Users/runner/miniconda3/pkgs -path '*/bzip2-*/info/licenses/*'
          for path in "${SEARCH_PATHS[@]}"; do
            echo "--- Searching in $path"
            for dylib in $(find "$path" -name "*libbz2*.dylib" 2>/dev/null); do
              echo "=== FOUND: $dylib"
              otool -D "$dylib" 2>/dev/null || echo "(otool failed)"
              echo "--- dependencies:"
              otool -L "$dylib" 2>/dev/null || echo "(otool -L failed)"
              echo ""
            done
          done
